### ISSUE TITLE
IP addresses are in pipeline e2e step logs

### ISSUE THREAD

**Issue by mraarone** [defenseunicorns/zarf-package-software-factory#263]
I was reviewing your logs to see how you set up your testing in your DevOps pipeline and ran across an AWS EC2 ip address. This could be used by someone wanting to attack your large testing host (it was not a free tier AWS EC2 instance). 

Also, image k3s downloads fill logs with download status which truncates e2e step logs.

**Comment by RothAndrew** [comment]
I believe the risk is minimal, and acceptable

* Great care has been taken to ensure that the SSH key is not exposed in the pipeline logs
* The SSH key is created right before the pipeline runs and deleted right after it
* The instance only lives for a short time. A new one is created/destroyed for each pipeline run

Happy to talk through how it can be improved though.

@jeff-mccoy thoughts?

---

I agree the logs are annoying when they get filled with junk. Need to fix that but it's not a very high priority right now. If you want to take a stab at it feel free to submit a PR.

If you click the gear icon at the top right of the window there is a "download log archive" button that gives you the full log that is not truncated.

**Comment by RothAndrew** [comment]
I went and looked at CloudPosse's setup (which this one is based on). They also log the public IP, which makes me even more comfortable with this, since they've been doing these kinds of tests for a few years now.

Not saying it can't be improved, but it likely isn't a problem.

https://github.com/cloudposse/actions/runs/6378682007?check_suite_focus=true#step:9:206

**Comment by RothAndrew** [comment]
Created #268 for the pipeline logs stuff.

**Comment by RothAndrew** [comment]
Closing for now. Happy to reopen if needed.
