### ISSUE TITLE
Explore changing zarf repo strings to specific tags/branches

### ISSUE THREAD

**Issue by corang** [defenseunicorns/zarf-package-software-factory#589]
Syncing an entire repo is kinda wasteful and causes problems when some random branch is force pushed, if we switched to specific refs package creation and deployment would likely be a bit quicker and you wouldn't have to worry about force pushes on branches you aren't using. 

See the zarf docs here https://docs.zarf.dev/examples/git-data/#git-reference-based-git-repository-clone

This comes with the downside of requiring end users of the package to need to update more things when customizing di2me for deployment, unsure if it's worth it. 

@anthonywendt @RothAndrew

**Comment by RothAndrew** [comment]
It pulls the whole repo so when you do a version update (like of Big Bang) you don't have to parse through and figure out which tags you need.

No objections here to pinning refs, as long as the people maintaining DI2-ME are okay with the increased maintenance overhead when doing version updates. Since that's not me any more for the most part you should do what works best for you :)

**Comment by corang** [comment]
I'm thinking on doing this probably for just the di2me repo. End user has to customize that string anyway so I don't think it'd be too much to have them also put in the branch/tag they're deploying from. Or in the end just leave it up to them what they do but default to a specific ref in this repo
